workflows:
  capacitor-android-apk:
    name: Capacitor Android APK
    max_build_duration: 60

    environment:
      node: 22.14.0
      java: 17

    cache:
      cache_paths:
        - ~/.npm

    scripts:
      - name: Install dependencies
        script: |
          pwd
          ls -la
          cd app-ai
          pwd
          ls -la
          node -v
          npm -v
          cat package.json
          npm ci --verbose

      - name: Build web app
        script: |
          cd app-ai
          npm run build

      - name: Sync Capacitor Android project
        script: |
          cd app-ai
          npx cap sync android

      - name: Build debug APK
        script: |
          cd app-ai/android
          ./gradlew assembleDebug --stacktrace

    artifacts:
      - app-ai/android/app/build/outputs/**/*.apk
