name: Build Victory APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build Process
        run: |
          npm install
          npm run build
          npx cap sync android
          cd android && ./gradlew assembleDebug
      - name: Get APK
        uses: actions/upload-artifact@v3
        with:
          name: victory-game-release
          path: android/app/build/outputs/apk/debug/app-debug.apk